version: '1.0'

services:
  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "81:81"
    depends_on:
      - db

  ui:
    container_name: ui
    image: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}